name: Publish Chart

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish-chart:
    uses: orhayoun-eevee/build-workflow/.github/workflows/on-merge-flow.yaml@main
    with:
      chart_path: .
      install_istio: true
      install_longhorn: true
      install_prometheus: true
    secrets: inherit  # Required for cross-repo workflows
 